#! /bin/sh

## ██████╗ ███████╗██████╗ ██╗    ██╗███╗   ███╗
## ██╔══██╗██╔════╝██╔══██╗██║    ██║████╗ ████║
## ██████╔╝███████╗██████╔╝██║ █╗ ██║██╔████╔██║
## ██╔══██╗╚════██║██╔═══╝ ██║███╗██║██║╚██╔╝██║
## ██████╔╝███████║██║     ╚███╔███╔╝██║ ╚═╝ ██║
## ╚═════╝ ╚══════╝╚═╝      ╚══╝╚══╝ ╚═╝     ╚═╝

###################
## configuration ##
###################

    # workspace names
    bspc monitor -d I II III IV V VI VII VIII IX X

    # general config
    bspc config border_width         3
    bspc config window_gap           20
    bspc config split_ratio          0.5
    bspc config borderless_monocle   true
    bspc config gapless_monocle      true

    # colors
    bspc config focused_border_color "#ffffff" 
    bspc config normal_border_color "#8b8b8b"

###############
## autostart ##
###############

    # display random wallpaper
    ~/bin/randbg.sh

    # caps as control when held, esc when pressed
    setxkbmap -option ctrl:nocaps
    xcape

    # disable trackpad
    ~/bin/toggle_trackpad.sh

    # enable notification service
    dunst

    # start compositor
    compton --backend glx --paint-on-overlay --vsync opengl-swc

    # hide cursor if not in use
    unclutter
